### ISSUE TITLE
Workflow steps don't scale with their content

### ISSUE THREAD

**Issue by kramlich-sandra** [siemens/ix#1090]
### Prerequisites

- [X] I have not leaked any internal company information.
- [X] I have not posted internal links or code snippets.

### What happened?

I used the workflow component inside a smaller div which was scaled to only use 40% of the whole screen. All my workflow steps then overflowed out of the screen. I found that the step has a predefined width which made it not scale to fit in my small div:  https://github.com/siemens/ix/blob/0c13d91562017bd3b5773fb3976b41d69fa037ab/packages/core/src/components/workflow-step/workflow-step.scss#L25

Also the property width is defined twice:
https://github.com/siemens/ix/blob/0c13d91562017bd3b5773fb3976b41d69fa037ab/packages/core/src/components/workflow-step/workflow-step.scss#L22

My workaround was to override this with in my code:
```css
// Cannot use step, because component uses .step already as class and then the changes don't get applied
.stepElement > div {
    width: auto !important;
    height: auto !important;
}
```

I would have expected the steps to scale so that they fit inside their parent container without getting too small.

### What type of frontend frameware are you seeing the problem on?

React

### Which version of iX do you use?

v1.6.3

### Code to produce this issue.

```shell
https://stackblitz.com/edit/react-lpbaev?file=src%2FApp.js
```
