### ISSUE TITLE
modal backdrop color not used and missmatch with figma

### ISSUE THREAD

**Issue by FabLax** [siemens/ix#1857]
### Prerequisites

- [x] I have read the [Contributing Guidelines](https://github.com/siemens/ix/blob/main/CONTRIBUTING.md).
- [x] I have not leaked any internal/restricted information like screenshots, videos, code snippets, links etc.

### What happened?

Backdrop of modal does not set the background-color and is therefore different to the one in figma.

Color variable is already there in the source code at /packages/core/src/components/modal/modal.scss

```css
::backdrop {
  --ix-dialog-backdrop: var(--theme-color-lightbox, #0000008c);
}
```
 
Fix is to just add `background-color: var(--ix-dialog-backdrop)` to the existing styling in same file

```css
  dialog::backdrop {
    backdrop-filter: blur(2.7182817459106445px);
  }
```

### What type of frontend framework are you seeing the problem on?

Angular

### Which version of iX do you use?

v3.0.0

### Code to produce this issue.

```shell
open a modal and check backdrop color
```
