### ISSUE TITLE
Map navigation: Customizable sidebar width

### ISSUE THREAD

**Issue by tomas-reznak** [siemens/ix#959]
### Suggestion / feature request

After migrating to iX 2.0.3, our sidebar within Map navigation is too wide and doesn't meet our needs. We would like to have the possibility to adjust the sidebar's width as needed.

Basically, we display list of [IxGroup](https://ix.siemens.io/docs/controls/group) components there and our workaround in previous versions was like this (but doesn't work anymore):

```css
 .map-nav-sidebar {
   width: 20rem !important;
   min-width: 20rem !important;
   max-width: 20rem !important;
 }
```
